### ISSUE TITLE
Has anyone tried extending Quill using jspm?

### ISSUE THREAD

**Issue by rokkamokka** [quilljs/quill#1210]
We've been looking at integrating Quill with our project, which uses jspm for js package management.

Installing quill via `jspm install npm:quill` works well, and extending types also seems to work well using something like:
```
import Quill from 'quill';
let Link = Quill.import('formats/link');
class ExtendedLink extends Link { ... }
```

However, we've run into issues when trying to extend SnowTheme. If we just copy the snow theme and change the import statements to:
```
import Emitter from 'quill/core/emitter';
import BaseTheme, { BaseTooltip } from 'quill/themes/base';
import LinkBlot from 'quill/formats/link';
import { Range } from 'quill/core/selection';
import icons from 'quill/ui/icons';
```

we get the following error message on transpiling

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
MultipleErrors: resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:3:1: Unexpected reserved word import
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:3:8: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:3:21: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:3:26: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:4:1: Unexpected reserved word import
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:4:8: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:4:15: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:4:20: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:36:1: Unexpected reserved word export
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:36:8: Semi-colon expected
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:36:8: Unexpected reserved word default
resources/assets/js/jspm_packages/npm/quill@1.1.7/core/emitter.js:36:16: Semi-colon expected
    (No stack trace)
From previous event:
    at Builder.buildStatic (/var/www/node_modules/systemjs-builder/lib/builder.js:635:4)
    at Builder.buildStatic (/var/www/node_modules/jspm/lib/bundle.js:108:48)
    at /var/www/node_modules/jspm/lib/bundle.js:213:26
    at tryCatchReject (/var/www/node_modules/when/es6-shim/Promise.js:1183:30)
    at runContinuation1 (/var/www/node_modules/when/es6-shim/Promise.js:1142:4)
    at Fulfilled.when (/var/www/node_modules/when/es6-shim/Promise.js:930:4)
    at Pending.run (/var/www/node_modules/when/es6-shim/Promise.js:821:13)
    at Scheduler._drain (/var/www/node_modules/when/es6-shim/Promise.js:97:19)
    at Scheduler.drain (/var/www/node_modules/when/es6-shim/Promise.js:62:9)
    at process._tickDomainCallback (node.js:459:13)
```

This seems to be because jspm tries to transpile this as CommonJS rather than ES6. If we provide an override for this in our package.json ...

```
    "overrides": {
      "npm:quill@1.1.7": {
        "format": "es6"
      }
    }
```

... we get other errors when trying to load ui/icons:

```
[BABEL] Note: The code generator has deoptimised the styling of "file:///var/www/resources/assets/js/jspm_packages/npm/quill@1.1.7/dist/quill.js" as it exceeds the max of "100KB".

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Error on fetch for npm:quill@1.1.7/assets/icons/dropdown.svg.js at file:///var/www/resources/assets/js/jspm_packages/npm/quill@1.1.7/assets/icons/dropdown.svg.js
        Loading npm:quill@1.1.7/ui/picker.js
        Loading npm:quill@1.1.7/themes/base.js
        Loading resources/assets/js/extensions/quill/themes/xsnow.js
        Loading resources/assets/js/main.js
        ENOENT, open '/var/www/resources/assets/js/jspm_packages/npm/quill@1.1.7/assets/icons/dropdown.svg.js'
    at Trace.getAllLoadRecords (/var/www/node_modules/systemjs-builder/lib/trace.js:567:4)
    at toCanonicalConditionalEnv.call.then.then.thisLoad (/var/www/node_modules/systemjs-builder/lib/trace.js:52:19)
    at Trace.traceCanonical (/var/www/node_modules/systemjs-builder/lib/trace.js:50:4)
    at /var/www/node_modules/systemjs-builder/lib/arithmetic.js:243:35
    at /var/www/node_modules/systemjs-builder/lib/arithmetic.js:232:20
    at Array.reduce (native)
    at processExpandedOperations (/var/www/node_modules/systemjs-builder/lib/arithmetic.js:231:35)
    at exports.traceExpression (/var/www/node_modules/systemjs-builder/lib/arithmetic.js:229:8)
    at Promise.resolve.then.then.self.tracer.inlineConditions.then.rollupTree.then.inlineMap (/var/www/node_modules/systemjs-builder/lib/builder.js:633:12)
    at Builder.buildStatic (/var/www/node_modules/systemjs-builder/lib/builder.js:626:4)
    at Builder.buildStatic (/var/www/node_modules/jspm/lib/bundle.js:108:48)
    at /var/www/node_modules/jspm/lib/bundle.js:213:26
    at tryCatchReject (/var/www/node_modules/when/es6-shim/Promise.js:1183:30)
    at runContinuation1 (/var/www/node_modules/when/es6-shim/Promise.js:1142:4)
    at Fulfilled.when (/var/www/node_modules/when/es6-shim/Promise.js:930:4)
    at Pending.run (/var/www/node_modules/when/es6-shim/Promise.js:821:13)
    at Scheduler._drain (/var/www/node_modules/when/es6-shim/Promise.js:97:19)
    at Scheduler.drain (/var/www/node_modules/when/es6-shim/Promise.js:62:9)
    at process._tickDomainCallback (node.js:459:13)
```

Judging from the error message, it seems to be trying to import the .svg files as .js files. Even if we try to remove the `import icons` statement in our custom theme, the error still occurs because `themes/base` imports `ui/picker` which imports `ui/icons`.

This is as far as we have gotten. Has anyone else done this, or does anyone have any ideas how to proceed?

**Version**:

jspm 0.16.33 and quill 1.1.7

**Comment by rokkamokka** [comment]
Just noticed that the ES6 override in package.json breaks importing and using dist/quill.js (even without the broken custom theme), so I wouldn't recommend going that route.


Error thrown by chrome 55 on windows 10 after importing quill with es6 override:
```
main.bundle-a909cb5d07.js:9049 Uncaught TypeError: Cannot set property 'Quill' of undefined
    at webpackUniversalModuleDefinition (main.bundle-a909cb5d07.js:9049)
    at execute (main.bundle-a909cb5d07.js:9049)
    at c (main.bundle-a909cb5d07.js:1)
    at c (main.bundle-a909cb5d07.js:1)
    at c (main.bundle-a909cb5d07.js:1)
    at f (main.bundle-a909cb5d07.js:1)
    at main.bundle-a909cb5d07.js:1
    at main.bundle-a909cb5d07.js:43296
    at main.bundle-a909cb5d07.js:1
    at main.bundle-a909cb5d07.js:43295
webpackUniversalModuleDefinition @ main.bundle-a909cb5d07.js:9049
execute @ main.bundle-a909cb5d07.js:9049
c @ main.bundle-a909cb5d07.js:1
c @ main.bundle-a909cb5d07.js:1
c @ main.bundle-a909cb5d07.js:1
f @ main.bundle-a909cb5d07.js:1
(anonymous) @ main.bundle-a909cb5d07.js:1
(anonymous) @ main.bundle-a909cb5d07.js:43296
(anonymous) @ main.bundle-a909cb5d07.js:1
(anonymous) @ main.bundle-a909cb5d07.js:43295
```

**Comment by rokkamokka** [comment]
So, through further trial and error, we've found something that seems to work.

The problem is two fold:
1. Some of the Quill js files are ES6, and some files are CommonJS. Furthermore, all of them (even the ES6 ones) have "format cjs", which also tricks jspm/systemjs.
2. jspm 0.16 has `defaultJSExtension = true`. which causes problems with the ui/icons.js when it requires .svg, since systemjs will then try to load .svg.js.

Both of these can be fixed with a custom package declaration in the systemjs config file:
```
  packages: {
    "quill": {
      "defaultExtension": "js",
      "format": "es6",
      "meta": {
        "dist/*": {
          "format": "cjs"
        },
        "ui/icons.js": {
          "format": "cjs"
        },
        "*.svg": {
          "loader": "svg"
        }
      }
    }
  },
```

We tell systemjs that everything is es6, except dist/* and ui/icons.js (probably needs more entries, but these two are enough to get a custom theme to work at least). We use `defaultExtension` to respect imports that specify other extensions (.svg). Finally, we tell it to load *.svg files using the svg plugin. Make sure the svg plugin is installed too (`jspm install svg`).

In the custom theme itself, we can't just import everything with ES6 either, some things seem to need to be Quill.import()ed to work.

```
import Emitter from 'quill/core/emitter';
import BaseTheme, {BaseTooltip} from 'quill/themes/base';
import {Range} from 'quill/core/selection';

import Quill from 'quill';
let LinkBlot = Quill.import('formats/link');
let icons = Quill.import('ui/icons');
```

After doing all this, custom themes transpile without errors and seem to work after being registered. :)

**Comment by rokkamokka** [comment]
We discovered another small kink with the above solution: the dropdown.svg icon for pickers was not loaded correctly. It showed up in the HTML as the string "[object Element]".

The fix is easy, however. In our systemsjs config, change the loader for "*.svg" from "svg" to "text" (and make sure to `jspm install text` so you have the necessary plugin).

**Comment by jhchen** [comment]
Sounds like you were able to find your own solution to your question. Thank you for sharing.
