### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by lietu555** [quilljs/quill#1629]
jianglin@JIANGLIN-WU:~/Desktop/web-text/quill$ npm run start

> quill@1.3.0 start /home/jianglin/Desktop/web-text/quill
> npm run build; bundle exec foreman start -f _develop/procfile

> quill@1.3.0 build /home/jianglin/Desktop/web-text/quill
> webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;

ts-loader: Using typescript@2.4.2 and /home/jianglin/Desktop/web-text/quill/node_modules/parchment/tsconfig.json
Hash: 466f8818c088cb7cb4b2
Version: webpack 3.4.1
Time: 12156ms
           Asset     Size  Chunks                    Chunk Names
         unit.js   579 kB       0  [emitted]  [big]  unit.js
        quill.js   429 kB       1  [emitted]  [big]  quill.js
   quill.core.js   299 kB       2  [emitted]  [big]  quill.core.js
      quill.snow  3.02 kB       3  [emitted]         quill.snow
      quill.core  3.02 kB       4  [emitted]         quill.core
    quill.bubble  3.02 kB       5  [emitted]         quill.bubble
  quill.core.css  9.07 kB       4  [emitted]         quill.core
quill.bubble.css  25.3 kB       5  [emitted]         quill.bubble
  quill.snow.css  24.8 kB       3  [emitted]         quill.snow
  [29] ./core.js 1.97 kB {0} {1} {2} [built]
 [109] multi ./quill.js 28 bytes {1} [built]
 [110] multi ./core.js 28 bytes {2} [built]
 [111] ./assets/core.styl 41 bytes {4} [built]
 [112] ./assets/bubble.styl 41 bytes {5} [built]
 [113] ./assets/snow.styl 41 bytes {3} [built]
 [114] ./test/unit.js 1.09 kB {0} [built]
 [124] ./test/unit/formats/link.js 2.13 kB {0} [built]
 [125] ./test/unit/formats/script.js 1.04 kB {0} [built]
 [126] ./test/unit/formats/align.js 1.77 kB {0} [built]
 [127] ./test/unit/formats/code.js 7.27 kB {0} [built]
 [128] ./test/unit/formats/header.js 1.4 kB {0} [built]
 [129] ./test/unit/formats/indent.js 1.09 kB {0} [built]
 [130] ./test/unit/formats/list.js 10 kB {0} [built]
 [131] ./test/unit/formats/bold.js 677 bytes {0} [built]
    + 123 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/core.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/core.styl 9.5 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/bubble.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/bubble.styl 26.4 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/snow.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/snow.styl 25.8 kB {0} [built]
        + 1 hidden module
sh: 1: bundle: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! quill@1.3.0 start: `npm run build; bundle exec foreman start -f _develop/procfile`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the quill@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jianglin/.npm/_logs/2017-08-07T08_36_51_472Z-debug.log

**Comment by capaj** [comment]
@jhchen why did you close this issue? I wanted to contribute to quill and I ran into the same exact issue.
This must have some solution and If I figure it out I will open a PR.

**Comment by capaj** [comment]
OKay I now realized that quill needs ruby and gems installed, so I did:
```
sudo snap install ruby
gem install bundler
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
bundle install
```

which got me farther, but it's still not runnig-now I get stuck here:
```
nr start

> quill@1.3.7 start /home/capaj/oss/quill
> npm run build; bundle exec foreman start -f _develop/procfile


> quill@1.3.7 build /home/capaj/oss/quill
> webpack --config _develop/webpack.config.js; rm dist/quill.core dist/quill.bubble dist/quill.snow;

Hash: 6001878ebbf5ab65f624
Version: webpack 3.12.0
Time: 4280ms
           Asset     Size  Chunks                    Chunk Names
         unit.js   611 kB       0  [emitted]  [big]  unit.js
        quill.js   453 kB       1  [emitted]  [big]  quill.js
   quill.core.js   320 kB       2  [emitted]  [big]  quill.core.js
      quill.snow  3.06 kB       3  [emitted]         quill.snow
      quill.core  3.06 kB       4  [emitted]         quill.core
    quill.bubble  3.06 kB       5  [emitted]         quill.bubble
  quill.core.css  9.02 kB       4  [emitted]         quill.core
quill.bubble.css  25.3 kB       5  [emitted]         quill.bubble
  quill.snow.css  24.7 kB       3  [emitted]         quill.snow
  [30] ./core.js 2.04 kB {0} {1} {2} [built]
 [122] multi ./quill.js 28 bytes {1} [built]
 [123] multi ./core.js 28 bytes {2} [built]
 [124] ./assets/core.styl 41 bytes {4} [built]
 [125] ./assets/bubble.styl 41 bytes {5} [built]
 [126] ./assets/snow.styl 41 bytes {3} [built]
 [127] ./test/unit.js 1.28 kB {0} [built]
 [136] ./test/unit/formats/color.js 1.8 kB {0} [built]
 [138] ./test/unit/formats/script.js 1.04 kB {0} [built]
 [139] ./test/unit/formats/align.js 1.77 kB {0} [built]
 [140] ./test/unit/formats/code.js 9.13 kB {0} [built]
 [141] ./test/unit/formats/header.js 1.4 kB {0} [built]
 [142] ./test/unit/formats/indent.js 1.09 kB {0} [built]
 [143] ./test/unit/formats/list.js 10 kB {0} [built]
 [144] ./test/unit/formats/bold.js 677 bytes {0} [built]
    + 136 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/core.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/core.styl 9.45 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/bubble.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/bubble.styl 26.3 kB {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/stylus-loader/index.js!assets/snow.styl:
       [0] ./node_modules/css-loader!./node_modules/stylus-loader!./assets/snow.styl 25.8 kB {0} [built]
        + 1 hidden module
17:46:29 jekyll.1  | started with pid 384
17:46:29 karma.1   | started with pid 385
17:46:29 webpack.1 | started with pid 387
17:46:29 proxy.1   | started with pid 389
17:46:29 jekyll.1  | /snap/ruby/151/lib/ruby/2.6.0/x86_64-linux/rbconfig.rb:13:in `<module:RbConfig>': ruby lib version (2.6.4) doesn't match executable version (2.5.5) (RuntimeError)
17:46:29 jekyll.1  |    from /snap/ruby/151/lib/ruby/2.6.0/x86_64-linux/rbconfig.rb:11:in `<top (required)>'
17:46:29 jekyll.1  |    from /snap/ruby/151/lib/ruby/2.6.0/rubygems.rb:9:in `require'
17:46:29 jekyll.1  |    from /snap/ruby/151/lib/ruby/2.6.0/rubygems.rb:9:in `<top (required)>'
17:46:29 jekyll.1  |    from <internal:gem_prelude>:2:in `require'
17:46:29 jekyll.1  |    from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
17:46:29 proxy.1   | Proxy listening on 9000
17:46:29 jekyll.1  | exited with code 1
17:46:29 system    | sending SIGTERM to all processes
17:46:29 karma.1   | terminated by SIGTERM
17:46:29 webpack.1 | terminated by SIGTERM
17:46:29 proxy.1   | terminated by SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quill@1.3.7 start: `npm run build; bundle exec foreman start -f _develop/procfile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quill@1.3.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
