### ISSUE TITLE
document.execCommand and ancient/future browsers

### ISSUE THREAD

**Issue by mike-grinspan** [quilljs/quill#1639]
Hi, one of my users are hit with an error immediately upon loading the page. I understand that the browsers affected are not supported, but it's a super simple fix.

**Steps for Reproduction**
1. Open any page that loads Quill's js.
    - (In this case, the page doesn't actually make use of Quill, but I don't think that matters.)

**Expected behavior**:
Nothing spectacular happens.

**Actual behavior**:
An error is thrown.

**Platforms**:
Operating System: Windows 7
Browser: Internet Explorer 10, Firefox 15, or Opera 12

**Version**:
1.3.1

The last few lines of /core/polyfill.js attempt to execute 2 commands that may or may not be supported by the browser. IE 10 will throw "Invalid argument", Firefox will throw "NS_ERROR_NOT_IMPLEMENTED", and Opera will throw "NOT_SUPPORTED_ERR". Checking if these commands are supported via `document.queryCommandSupported` and `document.queryCommandEnabled` would fix this issue. Note that IE and some versions of Firefox will also throw on `document.queryCommandEnabled` if the command is not supported, and some browsers don't support `document.queryCommandEnabled`. My fix covers both of these cases.

My fix would be to replace both calls to `document.execCommand` with the following;
```
var execCommand = function (command, showUI, value) {
    if(document.queryCommandSupported(command) && (typeof document.queryCommandEnabled === 'function' ? document.queryCommandEnabled(command) : true)) {
        try {
            return document.execCommand(command, showUI, value);
        } catch(e) {}
    }

    return false;
};

execCommand('enableObjectResizing', false, false);
execCommand('autoUrlDetect', false, false);
```

Aside from supporting these ancient older browsers, this would also prevent breaks in future browsers when any specific command is deprecated and removed.

**Comment by jhchen** [comment]
Every line of code is a liability, so each must justify their existence. As you say Quill does not support these browsers so this is outside its scope of responsibility. If future browsers change their APIs, Quill will update accordingly.

**Comment by pmarreck** [comment]
Just FYI, I'm getting this error output to stderr via `jsdom` when my mocha test suite runs (which is how I landed here via Googling, and interestingly, via ChatGPT when I gave it the stack trace!).

It's kind of futile to declare a virtual DOM to be an "unsupported browser" unless you hate testing. Also, feature testing before acting on said feature is pretty much a hallmark of coding and does ensure robustness against future changes at some admittedly slight upfront cost- Quill's test suite would just need coverage for this difference, for example.

This is all moot, of course, since Quill is effectively dead (is there a good fork?), but I'm not yet in a position to replace Quill yet. Fortunately, this error isn't breaking my suite (somehow...)

For the record (in case anyone else lands here), here's the output I'm getting, which I don't know if I should treat as a failure or not as it probably doesn't occur in a "real" browser (pardon my `PS1` noise, I'm going to make it more copy-friendly soon):

```
 20230127143336  …/mpnetwork   yolo !    v1.14.2 pmarreck  mocha

Error: Uncaught [TypeError: document.execCommand is not a function]
    at reportException (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
    at invokeEventListeners (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at DocumentImpl._dispatch (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at fireAnEvent (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at dispatchEvent (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:455:9)
    at /home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:460:11
    at new Promise (<anonymous>)
    at onDOMContentLoad (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:458:14)
    at Object.check (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
    at /home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:119:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5) TypeError: document.execCommand is not a function
    at Document.<anonymous> (/home/pmarreck/Documents/mpnetwork/assets/node_modules/quill/dist/quill.js:7720:12)
    at Document.callTheUserObjectsOperation (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
    at invokeEventListeners (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at DocumentImpl._dispatch (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at fireAnEvent (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at dispatchEvent (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:455:9)
    at /home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:460:11
    at new Promise (<anonymous>)
    at onDOMContentLoad (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:458:14)
    at Object.check (/home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
    at /home/pmarreck/Documents/mpnetwork/assets/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:119:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  34 passing (142ms)


 20230127143340  …/mpnetwork   yolo !    v1.14.2 pmarreck  echo $?
0
```
