### ISSUE TITLE
how to build quill after adding my own modules?

### ISSUE THREAD

**Issue by shengxiuzhou** [quilljs/quill#1849]
I have server problem when using quill, first I don't know how to add a button in the toolbar, is there any instructions to tell me how to implement it the way like "bold" not by using addEventListener。 second，I don't know how to build the quill after I add my own modules, since I only want to require quill.js in my page.

**Comment by benbro** [comment]
Custom button [example](https://codepen.io/anon/pen/PGRQrx).

Build:
http://quilljs.com/guides/adding-quill-to-your-build-pipeline/
https://github.com/quilljs/webpack-example

Development:
https://github.com/quilljs/quill/blob/develop/.github/DEVELOPMENT.md

**Comment by michael-y-1342** [comment]
the guide in:
https://github.com/quilljs/quill/blob/develop/.github/DEVELOPMENT.md
is not working for me for some reason.
i get:

Error: Cannot find module 'C:\Users\miyaron\Downloads\quill-develop\quill-develop\_develop\webpack.config.js;'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:115:13)
    at requireConfig (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:117:6)
    at C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at yargs.parse (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:228:39)
    at Object.parse (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:206:8
    at Object.<anonymous> (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:500:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\miyaron\Downloads\quill-develop\quill-develop\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
