### ISSUE TITLE
Can't build quill (windows)

### ISSUE THREAD

**Issue by michael-y-1342** [quilljs/quill#2582]
the guide in:
https://github.com/quilljs/quill/blob/develop/.github/DEVELOPMENT.md
is not working for me for some reason.
when following it, when running "npm run build" i get:

Error: Cannot find module 'C:\Users\michaelsm\Downloads\quill-develop\quill-develop_develop\webpack.config.js;'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
at WEBPACK_OPTIONS (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:115:13)
at requireConfig (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:117:6)
at C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:124:17
at Array.forEach ()
at module.exports (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\convert-argv.js:122:15)
at yargs.parse (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:228:39)
at Object.parse (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
at C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:206:8
at Object. (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack-cli\bin\cli.js:500:3)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object. (C:\Users\michaelsm\Downloads\quill-develop\quill-develop\node_modules\webpack\bin\webpack.js:156:2)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:282:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1

the first line seems strange:
"Error: Cannot find module 'C:\Users\michaelsm\Downloads\quill-develop\quill-develop_develop\webpack.config.js;'"
why the file name ends with ';'?

Any ideas?
Thanks.

**Comment by MachineMitch21** [comment]
It looks like most of the development must be done on OSX or Linux.  The reason it won't build is because the scripts section of package.json is incompatible with Windows CLI.  I had to make several changes in order for it to complete the process.  

I pushed the changes to my fork which you can take a look at if you want to do the same to yours.  I am going to open up a discussion here about this to see if these changes should go into the original repo or not.

Here is the link to my changes to package.json: https://github.com/MachineMitch21/quill/commit/6380628a756c40ca830b04b3bc8e74f37f4f32f0

Here is a link to changes I had to make to the Gemfile as well to satisfy those dependencies: https://github.com/MachineMitch21/quill/commit/e4efd174ae79751822c1b153f457ce56b2a0384e

Note that my changes are not the ones present in the .lock files as npm does all of that.

To outline what I did:
  1.  I had to change all the instances of semi-colons in the package.json "scripts" to ' & ' to seperate the different commands.
  2.  I had to change the 'rm' command in "build:webpack" to be this:
(rm dist/quill.core dist/quill.bubble dist/quill.snow || del /Q /F \".\\dist\\quill.core\" \".\\dist\\quill.bubble\" \".\\dist\\quill.snow\") because Windows doesn't have a rm command to delete files and instead uses the del command.  

Sorry for that big ugly block of CLI code, but I just wanted to sort of outline the changes I had to make.

Hopefully that puts you on the right path if you haven't already solved your problem.

**Comment by michael-y-1342** [comment]
wow that great!
I actually tried running in linux, and i could build, after solving 1 issue on the way.
still, trying to run tests (npm test) is not working, which is something I would like...

**Comment by MachineMitch21** [comment]
I couldn't get that to work either.  I'm not too familiar with the testing tools used for this project, though, unfortunately.

**Comment by MachineMitch21** [comment]
What is the error when you try running that?

**Comment by michael-y-1342** [comment]
i had an error regarding CHROME_BIN evn var, but i then set this en var to the location of chrome in puppeteer, now it says chrome is not responding...

**Comment by usernamedd** [comment]
the build problem hits me on ubuntu 20.there are so many errors especially from enlist. any one has a fork thay fluently builds on ubuntu.it has taken me 2 days.god

**Comment by benbro** [comment]
Please try https://github.com/quilljs/quill/blob/main/.github/DEVELOPMENT.md
