### ISSUE TITLE
Start using semantic versioning.

### ISSUE THREAD

**Issue by Matzz** [quilljs/quill#3256]
Recently there was a lot of bugs between version 3.5.2 and 3.5.3.
My organisation was also hit due to that because some stuff started to explode at runtime:
```
io.getquill.quotation.QuatException: Was expecting SQL-level type must be a Product but found `N`
	at io.getquill.quotation.QuatException$.apply(QuatException.scala:8)
	at io.getquill.quat.Quat.probit(Quat.scala:48)
	at io.getquill.quat.Quat.probit$(Quat.scala:45)
	at io.getquill.quat.Quat$Null$.probit(Quat.scala:218)
	at io.getquill.quat.Quat$Product$.fromSerializedJVM(Quat.scala:192)
```

And I must say that from the changelog between 3.5.2 and 3.5.3 I wouldn't expect such huge code changes. Even code migration was not so easy because some traits were moved (eg import io.getquill.context.cassandra.Udt to import io.getquill.Udt).

I think it would be beneficial for Quill users to mark such huge changes with "minor" number.
See https://semver.org/

**Comment by Matzz** [comment]
Sorry wrong repo
