### ISSUE TITLE
eslint blots core formats modules themes ui test

### ISSUE THREAD

**Issue by youfeed** [quilljs/quill#3408]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle quill@2.0.0-dev.4~prebuild: quill@2.0.0-dev.4
6 info lifecycle quill@2.0.0-dev.4~build: quill@2.0.0-dev.4
7 verbose lifecycle quill@2.0.0-dev.4~build: unsafe-perm in lifecycle true
8 verbose lifecycle quill@2.0.0-dev.4~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Micateam\Desktop\quill-develop\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NetSarang\Xshell 7\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Geth;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Go\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Micateam\AppData\Local\Microsoft\WindowsApps;C:\Users\Micateam\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Bandizip\;C:\Users\Micateam\AppData\Roaming\npm;C:\Program Files\GPAC;C:\Users\Micateam\Desktop\ffmpeg\bin;C:\Users\Micateam\go\bin;C:\Users\Micateam\AppData\Local\Programs\APICloud Studio 3\bin;C:\Flutter\bin;D:\Program Files\Nox\bin;
9 verbose lifecycle quill@2.0.0-dev.4~build: CWD: C:\Users\Micateam\Desktop\quill-develop
10 silly lifecycle quill@2.0.0-dev.4~build: Args: [ '/d /s /c', 'npm run lint && npm run build:webpack' ]
11 silly lifecycle quill@2.0.0-dev.4~build: Returned: code: 1  signal: null
12 info lifecycle quill@2.0.0-dev.4~build: Failed to exec build script
13 verbose stack Error: quill@2.0.0-dev.4 build: `npm run lint && npm run build:webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid quill@2.0.0-dev.4
15 verbose cwd C:\Users\Micateam\Desktop\quill-develop
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error quill@2.0.0-dev.4 build: `npm run lint && npm run build:webpack`
22 error Exit status 1
23 error Failed at the quill@2.0.0-dev.4 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by usernamedd** [comment]
the same problem . 
the solution :
open  file  package.json , modify scripts section :
  "lint": "eslint blots core formats modules themes ui test",   
        **to**
 "lint": "eslint **--fix** blots core formats modules themes ui test",

**Comment by benbro** [comment]
Please test [v2.0.0-rc.2](https://github.com/quilljs/quill/releases/tag/v2.0.0-rc.2)
