### ISSUE TITLE
Cannot read properties of undefined (reading 'register')

### ISSUE THREAD

**Issue by LXCGH** [quilljs/quill#3659]
version：
"vue-quill-editor": "^3.0.6",
"quill-image-resize-module": "^3.0.0",
"@vue/cli-plugin-babel": "~4.5.13",

question: why is the error reported in this way?

import VueQuillEditor, { Quill } from 'vue-quill-editor'
import { ImageResize } from 'quill-image-resize-module'

`Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at Function.register (quill.js?9339:1122:1)
    at eval (main.js?56d7:19:1)
    at ./src/main.js (app.js:1147:1)
    at __webpack_require__ (app.js:859:30)
    at fn (app.js:151:20)
    at 1 (app.js:1256:18)
    at __webpack_require__ (app.js:859:30)
    at checkDeferredModules (app.js:46:23)
    at app.js:1040:18
    at app.js:1043:10`

**Comment by LXCGH** [comment]
I have a problem with my writing

**Comment by LXCGH** [comment]
I have a problem with my writing

**Comment by divrawat** [comment]
I am facing this same error whats the solution ?
