### ISSUE TITLE
Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid

### ISSUE THREAD

**Issue by RRiggs13** [quilljs/quill#3742]
Under the "right circumstances", clicking any toolbar button in the Quill editor will generate the console error from the title.

**Steps for Reproduction**

1. From an "empty" editor (can be freshly instantiated, or simply cleared by setting '\n' as the contents)
2. Type "asdf" <new line> "asdf" (need at least two lines, can be many more added - same result)
3. Without doing anything else - the input cursor remains at the end of the second line
4. Click on any button in the toolbar and the console error will be generated and the button click does nothing
5. Simply move the cursor up a line, or back one character, then clicking on the toolbar works as expected

Additional notes
Moving the cursor around, but then back to the end of that last input line, w/o doing anything else, still generates the error.
Move the cursor, click a toolbar button - no error, move back to end of buffer, click button - no error

**Expected behavior**:
The clicked toolbar button action should execute

**Actual behavior**:
Nothing happens in the editor, and the console generates the Error

**Platforms**:
Mac OS - Catalina, Chrome Version 108.0.5359.124
Include browser, operating system and respective versions

**Version**:
Quill Editor v1.3.7

Stack Trace:
core.js:6498 ERROR DOMException: Failed to execute 'setStart' on 'Range': The offset 4294967295 is invalid.
    at Selection.setNativeRange (http://localhost/sf/ui/node_modules_quill_dist_quill_js.js:4142:23)
    at Selection.setRange (http://localhost/sf/ui/node_modules_quill_dist_quill_js.js:4168:35)
    at Selection.focus (http://localhost/sf/ui/node_modules_quill_dist_quill_js.js:3850:18)
    at Quill.focus (http://localhost/sf/ui/node_modules_quill_dist_quill_js.js:1643:28)
    at HTMLButtonElement.<anonymous> (http://localhost/sf/ui/node_modules_quill_dist_quill_js.js:12342:28)
    at e.invokeTask (http://localhost/sf/ui/scripts.js:11505:7889)
    at Object.onInvokeTask (http://localhost/sf/ui/vendor.js:207701:25)
    at e.invokeTask (http://localhost/sf/ui/scripts.js:11505:7810)
    at t.runTask (http://localhost/sf/ui/scripts.js:11505:2952)
    at t.invokeTask [as invoke] (http://localhost/sf/ui/scripts.js:11505:9021)
    at y (http://localhost/sf/ui/scripts.js:11536:703)
    at _ (http://localhost/sf/ui/scripts.js:11536:973)
    at HTMLButtonElement.m (http://localhost/sf/ui/scripts.js:11536:1253)

**Comment by ektak26** [comment]
Did you find a solution?

**Comment by Tangchony** [comment]
Same problem

**Comment by kaykie** [comment]
Same problem

**Comment by transtone** [comment]
same problem

**Comment by thanaism** [comment]
same problem

**Comment by aehyok** [comment]
same problem

**Comment by wail55** [comment]
same problem

**Comment by wcqwork** [comment]
I have the same problem, is there a solution

**Comment by shareefalis** [comment]
Use Quill 2.0
