### ISSUE TITLE
Building failed wit nodejs 4.2.1

### ISSUE THREAD

**Issue by lygstate** [quilljs/quill#502]
ERROR in ./src/index.js
Module parse failed: C:\CI-Cor\ks\editors\quill\src\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Authorship from './modules/authorship';
| import ImageTooltip from './modules/image-tooltip';
| import Keyboard from './modules/keyboard';
 @ multi quill

ERROR in ./test/quill.js
Module parse failed: C:\CI-Cor\ks\editors\quill\test\quill.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Quill from '../src/index';
|
| import EditorTests from './unit/editor';
webpack: bundle is now VALID.
18 10 2015 10:20:40.204:INFO [Chrome 45.0.2454 (Windows 7 0.0.0)]: Connected on socket CATiWnMa6IJVhy7bAAAA with id 38788269
Chrome 45.0.2454 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.009 secs / 0 secs)
[10:20:40] 'karma:test' errored after 4.89 s
[10:20:40] Error: 1
    at formatError (C:\CI-Cor\ks\bolt\bolt-sdk\nodejs\npm\node_modules\gulp-cli\index.js:197:10)
    at Gulp.<anonymous> (C:\CI-Cor\ks\bolt\bolt-sdk\nodejs\npm\node_modules\gulp-cli\index.js:223:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (C:\CI-Cor\ks\editors\quill\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at C:\CI-Cor\ks\editors\quill\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (C:\CI-Cor\ks\editors\quill\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\CI-Cor\ks\editors\quill\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at removeAllListeners (C:\CI-Cor\ks\editors\quill\node_modules\karma\lib\server.js:332:7)
    at Server.<anonymous> (C:\CI-Cor\ks\editors\quill\node_modules\karma\lib\server.js:343:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:428:9)
    at process._tickCallback (node.js:350:17)

**Comment by jhchen** [comment]
Try the master branch if you want to build Quill yourself. The develop branch is sometimes in flux.

**Comment by lygstate** [comment]
I am interested in getting it works again.
