### ISSUE TITLE
Ranges may be null in IE

### ISSUE THREAD

**Issue by jcludwig** [quilljs/quill#537]
We are seeing some issues on IE where it looks like Ranges can be null. Perhaps just a simple null check guard would be sufficient. Here is an example stack trace:

TypeError: Unable to get property 'isCollapsed' of undefined or null reference
at b.prototype.removeLink (local://pq.microsoft.com/minerva/scripts/quill.min.js:8:6483)
at Anonymous function (local://pq.microsoft.com/minerva/scripts/quill.min.js:8:5653)
at Anonymous function (local://pq.microsoft.com/minerva/scripts/quill.min.js:7:18036)

**Comment by jhchen** [comment]
There's now a more robust way for saving/tracking the range (which is null here) and should be in the next version. What versions of IE is this affecting?

**Comment by jcludwig** [comment]
11.0.10240.16431

**Comment by jhchen** [comment]
This has been fixed in the 1.0 [beta](http://beta.quilljs.com/) release
