### ISSUE TITLE
Build fails in node 6 (v6.2.1)

### ISSUE THREAD

**Issue by saw** [quilljs/quill#732]
When attempting to build in node 6 the build fails with an error in parchment, this happens in master, 1.0 and develop:

```
ERROR in ./~/parchment/src/parchment.ts
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at ensureTypeScriptInstance (/Users/stephen.woods/Code/hax/quill/node_modules/ts-loader/index.js:156:103)
    at Object.loader (/Users/stephen.woods/Code/hax/quill/node_modules/ts-loader/index.js:403:14)
 @ ./core.js 7:17-37
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Steps for Reproduction**

1. Install node v6.2.1
2. Clone the quill repo
3. npm install, sudo gem install foreman jekyll kramdown rouge jekyll-sitemap jekyll-redirect-from jekyll-feed; npm run build

**Expected behavior**: Builds

**Actual behavior**: Throws above error

**Platforms**: Mac OS X 10.11.5

**Version**: master/develop/1.0 branch, tested with a9f38c1c3a7f4703ae2ad319997405031d35ddf4

**Comment by saw** [comment]
(downgrading to node v.4.4.5 fixes the error)
